version: '2'

services:

    main:
        image: alterrebe/postfix-relay
        environment:
           - EXT_RELAY_HOST=${MAIL_SERVER}
           - EXT_RELAY_PORT=${MAIL_PORT}
           - SMTP_LOGIN=${MAIL_USERNAME}
           - SMTP_PASSWORD=${MAIL_PASSWORD}
           - USE_TLS=yes
        ports:
            - 25
        networks:
            back:
                aliases:
                    - mail
        volumes:
            - main_data:/var/spool/postfix
        tmpfs:
            - /run
            - /tmp
networks:
    back:
        external:
            name: "puffin_back"
volumes:
    main_data:
